// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
var SupplyChain = artifacts.require('SupplyChain')

contract('SupplyChain', function(accounts) {
    // Declare few constants and assign a few sample accounts generated by ganache-cli
    const sku = 1
    const upc = 1
    const ownerID = accounts[0]
    const originFarmerID = accounts[1]
    const originFarmName = "John Doe"
    const originFarmInformation = "Yarray Valley"
    const originFarmLatitude = "-38.239770"
    const originFarmLongitude = "144.341490"
    const productID = sku + upc
    const productNotes = "Best beans for Espresso"
    const productPrice = web3.utils.toWei("1", "ether")
    const itemState = 0
    const distributorID = accounts[2]
    const retailerID = accounts[3]
    const consumerID = accounts[4]
    const emptyAddress = '0x00000000000000000000000000000000000000'
    let supplyChain

    ///Available Accounts
    ///==================
    ///(0) 0x27d8d15cbc94527cadf5ec14b69519ae23288b95
    ///(1) 0x018c2dabef4904ecbd7118350a0c54dbeae3549a
    ///(2) 0xce5144391b4ab80668965f2cc4f2cc102380ef0a
    ///(3) 0x460c31107dd048e34971e57da2f99f659add4f02
    ///(4) 0xd37b7b8c62be2fdde8daa9816483aebdbd356088
    ///(5) 0x27f184bdc0e7a931b507ddd689d76dba10514bcb
    ///(6) 0xfe0df793060c49edca5ac9c104dd8e3375349978
    ///(7) 0xbd58a85c96cc6727859d853086fe8560bc137632
    ///(8) 0xe07b5ee5f738b2f87f88b99aac9c64ff1e0c7917
    ///(9) 0xbd3ff2e3aded055244d66544c9c059fa0851da44

    console.log("ganache-cli accounts used here...")
    console.log("Contract Owner: ", ownerID)
    console.log("Farmer: ", originFarmerID)
    console.log("Distributor: ", distributorID)
    console.log("Retailer: ", retailerID)
    console.log("Consumer: ", consumerID)

    before(async () => {
        supplyChain = await SupplyChain.deployed()
    });

    // 1st Test
    it("Testing smart contract function harvestItem() that allows a farmer to harvest coffee", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event Harvested()
        supplyChain.contract.events.Harvested({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as Harvested by calling function harvestItem()
        await supplyChain.addFarmer(originFarmerID);
        await supplyChain.harvestItem(
            upc,
            originFarmerID,
            originFarmName,
            originFarmInformation,
            originFarmLatitude,
            originFarmLongitude,
            productNotes,
        )

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBufferOne = await supplyChain.fetchItemBufferOne.call(upc)
        const resultBufferThree = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBufferOne[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBufferOne[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBufferOne[2], originFarmerID, 'Error: Missing or Invalid originFarmerID')
        assert.equal(resultBufferOne[3], originFarmName, 'Error: Missing or Invalid originFarmName')
        assert.equal(resultBufferOne[4], originFarmInformation, 'Error: Missing or Invalid originFarmInformation')
        assert.equal(resultBufferOne[5], originFarmLatitude, 'Error: Missing or Invalid originFarmLatitude')
        assert.equal(resultBufferOne[6], originFarmLongitude, 'Error: Missing or Invalid originFarmLongitude')
        assert.equal(resultBufferThree[2], originFarmerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBufferThree[3], 0, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 2nd Test
    it("Testing smart contract function processItem() that allows a farmer to process coffee", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event Processed()
        supplyChain.contract.events.Processed({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as Processed by calling function processtItem()
        await supplyChain.processItem(upc, {from: originFarmerID})

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBuffer[2], originFarmerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBuffer[3], 1, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 3rd Test
    it("Testing smart contract function packItem() that allows a farmer to pack coffee", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event Packed()
        supplyChain.contract.events.Packed({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as Packed by calling function packItem()
        await supplyChain.packItem(upc, {from: originFarmerID})

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBuffer[2], originFarmerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBuffer[3], 2, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 4th Test
    it("Testing smart contract function sellItem() that allows a farmer to sell coffee", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event ForSale()
        supplyChain.contract.events.ForSale({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as ForSale by calling function sellItem()
        await supplyChain.sellItem(upc, productPrice, {from: originFarmerID})

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBuffer[2], originFarmerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBuffer[3], 3, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 5th Test
    it("Testing smart contract function buyItem() that allows a distributor to buy coffee", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event Sold()
        supplyChain.contract.events.Sold({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as Sold by calling function buyItem()
        await supplyChain.addDistributor(distributorID);
        await supplyChain.buyItem(upc, {from: distributorID, value: productPrice})

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBuffer[2], distributorID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBuffer[3], 4, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 6th Test
    it("Testing smart contract function shipItem() that allows a distributor to ship coffee", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event Shipped()
        supplyChain.contract.events.Shipped({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as shiped by calling function shipItem()
        await supplyChain.shipItem(upc, {from: distributorID})

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBuffer[2], distributorID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBuffer[3], 5, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 7th Test
    it("Testing smart contract function receiveItem() that allows a retailer to mark coffee received", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event Received()
        supplyChain.contract.events.Received({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as Received by calling function receiveItem()
        await supplyChain.addRetailer(retailerID);
        await supplyChain.receiveItem(upc, {from: retailerID})

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBuffer[2], retailerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBuffer[3], 6, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 8th Test
    it("Testing smart contract function purchaseItem() that allows a consumer to purchase coffee", async() => {
        // Declare and Initialize a variable for event
        var eventEmitted = false

        // Watch the emitted event Purchased()
        supplyChain.contract.events.Purchased({
            fromBlock: 0,
          }, (err, res) => {
            eventEmitted = true
        });

        // Mark an item as Purchased by calling function purchaseItem()
        await supplyChain.addConsumer(consumerID);
        await supplyChain.purchaseItem(upc, {from: consumerID})

        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)

        // Verify the result set
        assert.equal(resultBuffer[2], consumerID, 'Error: Missing or Invalid ownerID')
        assert.equal(resultBuffer[3], 7, 'Error: Invalid item State')
        assert.equal(eventEmitted, true, 'Invalid event emitted')
    })

    // 9th Test
    it("Testing smart contract function fetchItemBufferOne() that allows anyone to fetch item details from blockchain", async() => {
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferOne.call(upc)
        // Verify the result set:
        assert.equal(resultBuffer[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBuffer[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBuffer[2], originFarmerID, 'Error: Missing or Invalid originFarmerID')
        assert.equal(resultBuffer[3], originFarmName, 'Error: Missing or Invalid originFarmName')
        assert.equal(resultBuffer[4], originFarmInformation, 'Error: Missing or Invalid originFarmInformation')
        assert.equal(resultBuffer[5], originFarmLatitude, 'Error: Missing or Invalid originFarmLatitude')
        assert.equal(resultBuffer[6], originFarmLongitude, 'Error: Missing or Invalid originFarmLongitude')
    })

    // 10th Test
    it("Testing smart contract function fetchItemBufferTwo() that allows anyone to fetch item details from blockchain", async() => {
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferTwo.call(upc)
        // Verify the result set:
        assert.equal(resultBuffer[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBuffer[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBuffer[2], productID, 'Error: Missing or Invalid productID')
        assert.equal(resultBuffer[3], productNotes, 'Error: Missing or Invalid productNotes')
        assert.equal(resultBuffer[4], productPrice, 'Error: Missing or Invalid productPrice')
    })

    // 11th Test
    it("Testing smart contract function fetchItemBufferThree() that allows anyone to fetch item details from blockchain", async() => {
        // Retrieve the just now saved item from blockchain by calling function fetchItem()
        const resultBuffer = await supplyChain.fetchItemBufferThree.call(upc)
        // Verify the result set:
        assert.equal(resultBuffer[0], sku, 'Error: Invalid item SKU')
        assert.equal(resultBuffer[1], upc, 'Error: Invalid item UPC')
        assert.equal(resultBuffer[4], distributorID, 'Error: Missing or Invalid distributorID')
        assert.equal(resultBuffer[5], retailerID, 'Error: Missing or Invalid retailerID')
        assert.equal(resultBuffer[6], consumerID, 'Error: Missing or Invalid consumerID')
    })

});